### ISSUE TITLE
cindy.tan[Application] 

### ISSUE THREAD

**Issue by Cindy884** [dcdao/profiles#25]
### Nickname

Cindy

### Picture

193fcd13996842cfb6b970c11ab57044

### Role

Community Ambassador

### Address

0xc2B59Ecd40b8B54Bc23Bc395EefA0DEC3CCC6c5F

### Contribution

Establish DCDAO 
Moderate DCDAO community

### Google Forms(Optional)

- [X] I've filled the form.

**Comment by furoxr** [comment]
Application template has updated
