### ISSUE TITLE
[Application] 

### ISSUE THREAD

**Issue by 1022ranji** [dcdao/profiles#27]
### Nickname

Ran

### Picture

66bfdcf47c6448a7b0928e6f241d5a8e

### Role

Other-Contributor

### Address

0x2f2b799e8418d9D33C7fC8bD03a441E216cB6532

### Saying

IAMTHEBEST

### Contribution

<img width="696" alt="231104485-1d0d044b-ebfb-46ef-88aa-eceb18509d45" src="https://user-images.githubusercontent.com/80877629/231390073-b91df69c-f98d-40f5-bdd0-9cb271152283.png">
https://github.com/1022ranji?tab=overview&from=2021-06-01&to=2021-06-30

### Google Forms(Optional)

- [ ] I've filled the form.

**Comment by furoxr** [comment]
Closed as PR Release#1 (https://github.com/dcdao/profiles/pull/28) merged
