### ISSUE TITLE
[Application] echo

### ISSUE THREAD

**Issue by hujw77** [dcdao/profiles#35]
### Nickname

echo

### Picture

5fec7e61ee324179be7c370db9b724a1

### Role

Developer, Researcher

### Address

0x7aE77149ed38c5dD313e9069d790Ce7085caf0A6

### Saying

He who tells the truth is never wrong.

### Contribution

https://github.com/darwinia-network/darwinia-messages-sol/graphs/contributors

### Google Forms(Optional)

- [ ] I've filled the form.

**Comment by furoxr** [comment]
#30
