### ISSUE TITLE
[Application] JDubs

### ISSUE THREAD

**Issue by 2xJDubs** [dcdao/profiles#36]
### Nickname

JDubs

### Picture

1f67931be4e24562a9cd028ad42217d9

### Role

Ambassador

### Address

0xebd9A48eD1128375EB4383ED4d53478B4FD85a8D

### Saying

Don't sweat the small stuff, and it is all small stuff.

### Contribution

I have been an Ambassador for Darwinia since June of 2021.  I have worked hard to promote Darwinia to other communities and groups inside the Polkadot Eco.  For about 6 months in 2022 I worked with Megan and Dustin as part of the Business Development team.  Through the whole time I have been an admin in all of the Darwinia groups on Telegram and on the Discord server.  I provide frontline technical assistance to the Darwinia community as needed.

### Google Forms(Optional)

- [X] I've filled the form.

**Comment by Cindy884** [comment]
approved
