### ISSUE TITLE
[Application] Crypto Hustler 101

### ISSUE THREAD

**Issue by cryptohustler101** [dcdao/profiles#52]
### Nickname

Crypto Hustler 101

### Picture

6694574dde644040a4bd562bad5e5fdd

### Role

Ambassador

### Address

0xC1c3D0Cd8c23bDeC19b7F8D2601cc3b3B35c2629

### Saying

To selfless is to be selfish

### Contribution

I been apart of Itering in the early days of Evolution Land in 2018 becoming a advocate for the game, then became a Admin on TG for EvolutionLand. I since was early participant of Crab Network Testnet, then Darwinia advocating and eventually working with the team with the Evolution Land side. I have since been a huge advocate for Itering's suite of products including Helix, and Subscan. Darwinia is the reason why im in the Polkadot Space and have my loyalty to the project with deep respect for Alex and Denny for building these projects. I would be a huge asset in becoming a Dao member!

### Google Forms(Optional)

- [X] I've filled the form.

**Comment by Cindy884** [comment]
Hi there, thanks for your application. By now, we can't mint the NFT on your own photos, could you choose the picture based on our images directory? Here is the tutorial:)
<img width="779" alt="image" src="https://github.com/dcdao/profiles/assets/109792098/46fb5e31-1d58-4e37-9aaa-39339ae0aaa0">

**Comment by cryptohustler101** [comment]
https://github.com/dcdao/profiles/blob/main/images/6694574dde644040a4bd562bad5e5fdd.png update of the image i will be using.
