### ISSUE TITLE
[Application] Furqan Ahmed

### ISSUE THREAD

**Issue by nblogist** [dcdao/profiles#56]
### Nickname

furqan

### Picture

168c59241bc54e88a818d5030dae6a6b

### Role

Manager, Other-Contributor

### Address

0x822E4e429aDeDd91c96a81db39401A1770B96a5b

### Saying

Fate favors the bold.

### Contribution

Previously contributed to Subscan and Darwinia and now joining to contribute as integration specialist to connect the ecosystem of Darwinia!

[Resume](https://file.notion.so/f/f/b96e891c-c9b2-4cf5-be26-ebbb5a3f11e4/c8ab430b-b524-4c27-b288-03dd4a30f800/Furqan_Resume.pdf?id=a64fba99-838a-4450-b30a-cdfd9068acac&table=block&spaceId=b96e891c-c9b2-4cf5-be26-ebbb5a3f11e4&expirationTimestamp=1707091200000&signature=_c_Az3CGT7xBcqI2sHk3YOlyBaK1bwz_3UUl6K2p1cI&downloadName=Furqan+Resume.pdf)
[LinkedIn](http://linkedin.com/in/furqanAhmed18)
[Twitter](https://twitter.com/FurqandotAhmed)
[Telegram](https://t.me/furqan)

### Google Forms(Optional)

- [ ] I've filled the form.

**Comment by nblogist** [comment]
Is there any chance we can add more images in the folder?

**Comment by hackfisher** [comment]
> Is there any chance we can add more images in the folder? 

Yes, sure, we can do that by PR provided more images generated by some community artist or other methods.

**Comment by nblogist** [comment]
Okay! :) I think i am good with the one I selected rn!
