### ISSUE TITLE
[Application] Divblaze

### ISSUE THREAD

**Issue by Divblaze** [dcdao/profiles#62]
### Nickname

Divblaze

### Picture

720ec59d300a462580a650d6e788138d

### Role

Evangelist, Other-Contributor

### Address

0x2854759ff0136038F7326fCE6900D6eBF97eDD51

### Saying

Nil

### Contribution

Previously work with Darwinia network as a Translator 

### Google Forms(Optional)

- [X] I've filled the form.

**Comment by nblogist** [comment]
Hey @Divblaze thank you for your application - can you please share a little more about yourself and works with Darwinia.

**Comment by Divblaze** [comment]
Good day @nblogist thanks for the reply, I have been with Darwinia network since 2022 as an active community member and also helping in community translation

**Comment by nblogist** [comment]
Thank you for your response- can you please share some of your works and your most recent contribution with its date.

Looking forward to reviewing your application!

**Comment by Divblaze** [comment]
Okay

**Comment by Divblaze** [comment]
https://medium.com/@ekedivine2000/%E0%A8%A1%E0%A8%BE%E0%A8%B0%E0%A8%B5%E0%A8%BF%E0%A8%A8%E0%A9%80%E0%A8%86-%E0%A8%AC%E0%A9%8D%E0%A8%B0%E0%A8%BF%E0%A8%9C-1-2-%E0%A8%A8%E0%A9%82%E0%A9%B0-%E0%A8%B8%E0%A8%AE%E0%A8%9D%E0%A8%A3%E0%A8%BE-%E0%A8%AE%E0%A9%88%E0%A8%AA%E0%A8%BF%E0%A9%B0%E0%A8%97-%E0%A8%9F%E0%A9%8B%E0%A8%95%E0%A8%A8-%E0%A8%AB%E0%A9%88%E0%A8%95%E0%A8%9F%E0%A8%B0%E0%A9%80-cc9ee70840d7?source=user_profile---------15----------------------------


https://medium.com/@ekedivine2000/%E0%A8%88%E0%A8%B5%E0%A9%87%E0%A8%B2%E0%A9%82%E0%A8%B8%E0%A8%BC%E0%A8%A8-%E0%A8%B2%E0%A9%88%E0%A8%82%E0%A8%A1-2-%E0%A8%A8%E0%A8%B5%E0%A9%B0%E0%A8%AC%E0%A8%B0-%E0%A8%85%E0%A8%AA%E0%A8%A1%E0%A9%87%E0%A8%9F-%E0%A8%85%E0%A8%AA%E0%A9%8B%E0%A8%B8%E0%A8%9F%E0%A8%B2-%E0%A8%95%E0%A9%87%E0%A8%B5-%E0%A8%90%E0%A8%95%E0%A8%B8%E0%A8%AA%E0%A8%B2%E0%A9%8B%E0%A8%B0-%E0%A8%86%E0%A8%A8-%E0%A8%A6-%E0%A8%A1%E0%A8%BE%E0%A8%A8%E0%A8%BF%E0%A9%B0%E0%A8%97-%E0%A8%B8%E0%A8%BC%E0%A9%81%E0%A8%B0%E0%A9%82-%E0%A8%95%E0%A8%B0%E0%A9%8B-8673c38165a6?source=user_profile---------14----------------------------



https://medium.com/@ekedivine2000/%E0%A8%A1%E0%A8%BE%E0%A8%B0%E0%A8%B5%E0%A8%BF%E0%A8%A8%E0%A9%80%E0%A8%86-%E0%A8%AE%E0%A9%87%E0%A8%AE-%E0%A8%AE%E0%A9%81%E0%A8%95%E0%A8%BE%E0%A8%AC%E0%A8%B2%E0%A8%BE-c2d8c149c11f?source=user_profile---------13----------------------------



https://medium.com/@ekedivine2000/web3-0-metaverse-%E0%A8%B2%E0%A8%88-%E0%A8%85%E0%A8%97%E0%A8%B2%E0%A9%80-%E0%A8%AA%E0%A9%80%E0%A9%9C%E0%A9%8D%E0%A8%B9%E0%A9%80-%E0%A8%A6%E0%A9%87-%E0%A8%AC%E0%A9%81%E0%A8%A8%E0%A8%BF%E0%A8%86%E0%A8%A6%E0%A9%80-%E0%A8%A2%E0%A8%BE%E0%A8%82%E0%A8%9A%E0%A9%87-%E0%A8%B5%E0%A8%BF%E0%A9%B1%E0%A8%9A-%E0%A8%A8%E0%A8%BF%E0%A8%B5%E0%A9%87%E0%A8%B8%E0%A8%BC-%E0%A8%95%E0%A8%B0%E0%A8%A6%E0%A9%87-%E0%A8%B9%E0%A9%8B%E0%A8%8F-%E0%A8%A1%E0%A8%BE%E0%A8%B0%E0%A8%B5%E0%A8%BF%E0%A8%A8%E0%A9%80%E0%A8%86-%E0%A8%A6%E0%A8%BE-%E0%A8%B8%E0%A8%AE%E0%A8%B0%E0%A8%A5%E0%A8%A8-%E0%A8%95%E0%A8%B0%E0%A9%8B-7e9168b3d64d?source=user_profile---------12----------------------------

**Comment by Divblaze** [comment]
Some articles on Darwinia and evolution land

**Comment by Divblaze** [comment]
Would be expecting some reply soon

**Comment by Divblaze** [comment]
@furoxr

**Comment by Divblaze** [comment]
When will I be issued The NFT
