### ISSUE TITLE
[Application] Nada

### ISSUE THREAD

**Issue by furoxr** [dcdao/profiles#7]
Nickname: Nada
Picture: c6b2965dd9154de68b29c899552b4660
Role: Dev
Address: 0x573749FFee40b3aA6C080144D4071847c51B5C33
Contribution: Dev

**Comment by hackfisher** [comment]
@furoxr Should we close it now since https://github.com/dcdao/profiles/pull/10 being merged?

**Comment by hackfisher** [comment]
@furoxr Did the CI run successfully?

**Comment by furoxr** [comment]
Yes, CI has run successfully, we could close this issue.
